### ISSUE TITLE
Connection to https://unrelenting.technology/classyclock/static/settings.html broken

### ISSUE THREAD

**Issue by sidarous** [myfreeweb/classyclock#1]
Something with SSL?

Secure Connection Failed

The connection to unrelenting.technology was interrupted while the page was loading.

```
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.
```

**Comment by valpackett** [comment]
Something went wrong with my frontend server.
Restarted it, works fine now.

I should set up some monitoring... :D

**Comment by sidarous** [comment]
![screenshot_2015-12-18-11-54-15 1](https://cloud.githubusercontent.com/assets/14842990/11916589/e9edade0-a6a2-11e5-9f01-c0911fbe9582.png)
Now, when I go to the settings menu, I'm getting this after 5 minutes of
waiting. If I go to the settings page with a regular browser, it works
fine. Any ideas? I was seeing the same problem yesterday.

Things I've tried:
Rebooting
Removing app and reinstalling
Removing watchface and reinstalling

Settings pages for other watchfaces seem to work fine.

Samsung Galaxy S 4 connected to Pebble Time.

**Comment by valpackett** [comment]
I don't see your "this"! GitHub doesn't parse attachments.
