### ISSUE TITLE
Settings page removed from web?

### ISSUE THREAD

**Issue by ScuzzieScuzz** [myfreeweb/classyclock#2]
When trying to access settings page to update timetable now hitting blank/default page. Accidental take down? Or no longer supporting? Any info much appreciated, thanks.

**Comment by valpackett** [comment]
Yeah I changed servers and didn't deploy the app to the new server. I'll bring it up soon.

**Comment by ScuzzieScuzz** [comment]
Awww, brill. Thanks a lot. Honestly don't know what I'd do without it. (Actually, I do. I'd be late to every single one of my classes and I'd get fired.) Really appreciate it.

**Comment by ssehcs** [comment]
I am a teacher and I love classy clock.  Any update on settings page servers?

**Comment by valpackett** [comment]
Sorry for the delay, the server is back up.

**Comment by ScuzzieScuzz** [comment]
Heyo, popped on to take a quick gander and all I can see is a two-colour page with no options.

![21082239_10159246410090392_1268645234_o](https://user-images.githubusercontent.com/29440603/29690185-df88baca-891d-11e7-8075-76a817e5dfeb.png)

**Comment by valpackett** [comment]
Should work now

**Comment by ScuzzieScuzz** [comment]
Perfect. Thank you! Much appreciated :)
